---
title: "FEMA Individual and Household Assistance Funds"
format: 
  html:
    df-print: paged
    code-fold: true
    code-tools: true
    toc: true
    tbl-cap-location: margin
    fig-cap-location: margin
---

```{r setup, warning = FALSE, message = FALSE}
library(tidyverse)
library(modelsummary)
library(sf)
library(tmap)

library(tigris)



knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# all disasters in Illinois, filter in next step
#ind_assist <- read_csv("./inputs/data/indiv_assistance_CookCounty3.csv") |> 
 # filter(incidentType != "Biological" & disasterNumber != "1763") |>

city_names <- read_csv("./data/processed/City_Name_Mapping.csv")

ind_assist <- read_csv("./data/raw/indiv_assistance_V2_CookCounty.csv") |> 
  filter(incidentTypeCode != "B" & disasterNumber != "1763") |>
      mutate(year = str_sub(declarationDate, 1, 4),
             year = as.numeric(year),
             
             # for census shapefiles later
         joinyear = ifelse(
           year <= 2010, 2000, 
           ifelse(year < 2020 & year > 2010, 2010,
                  ifelse(year > 2020, 2020, year))),
         tract = str_sub(censusGeoid, 6, 9)
         ) |>
  mutate(tract = str_pad(tract, width = 6, pad = "0", side = "right")) |>
  left_join(city_names)

# all disasters in Cook County, IL
cook_assist <- ind_assist %>% filter(county == "Cook (County)" & disasterNumber != "4819")

# # Just Flood events in 2023
# ind_assist <- ind_assist %>% 
#   filter(county == "Cook (County)" & disasterNumber %in% c("4728", "4749") )

# Include other big flood events:
ind_assist <- ind_assist %>% 
  filter(county == "Cook (County)" & disasterNumber %in% c("4728", "4749", "1935", "4116") )

#table(ind_assist$damagedZipCode[ind_assist$disasterNumber=="1935"])
#table(ind_assist$damagedZipCode[ind_assist$disasterNumber=="4728"])
```

```{r blockgroup-shapefiles, include = FALSE, eval=FALSE, warning = FALSE, message=FALSE, results='hide'}

bg2000 <- block_groups(state = "17", county = "031", year=2000) %>% mutate(year = 2000)

bg2010 <- block_groups(state = "17", county = "031",year=2010) %>% mutate(year = 2010)

bg2020 <- block_groups(state = "17", county = "031", year=2020) %>% mutate(year = 2020)


bg2000 <- bg2000 |> 
  select(bg_id = BKGPIDFP00,
         tract = TRACTCE00,
         year)


bg2010 <- bg2010 |> 
  select(bg_id = GEOID10,
         tract = TRACTCE10,
         year)

bg2020 <- bg2020 |> 
  select(bg_id = GEOID,
         tract = TRACTCE,
         year)

blk_grps <- rbind(bg2000, bg2010, bg2020)

```

```{r make-blkgroup-maps-pdfs, eval=FALSE, include=FALSE}
years <- unique(blk_grps$year)

walk(years, ~ {
  p <- ggplot(filter(blk_grps, year == .x)) +
    geom_sf(fill = "white", color = "grey20") +
   # geom_sf_text(aes(label = bg_id), size = 1) +
    coord_sf() +
    theme_void() +
    labs(title = paste("Cook County BlockGroups —", .x))
  
  ggsave(filename = paste0("outputs/maps/cook_blk_groups_", .x, ".pdf"),
         plot = p,
         width = 8,
         height = 10)
})
```

```{r eval=FALSE, include=FALSE}
#| fig-label: fig-map-blkgroup-applicants
#| layout-ncol: 2

cook_assist |> 
  filter(disasterNumber == 4749 | disasterNumber == 4728 ) |>
  group_by(joinyear, disasterNumber, censusGeoid) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |>
  arrange(desc(claimcount))

cook_assist |> 
  filter((disasterNumber == 4749 | disasterNumber == 4728) & censusGeoid != "NULL" ) |>
  group_by(joinyear, disasterNumber, censusGeoid) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  left_join(blk_grps, by = c( "joinyear" = "year", "censusGeoid" = "bg_id")) %>%    

  ggplot(aes(fill = claimcount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "Applicants by Census Block Group & Disaster Declaration", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
   # nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
    labels = scales::comma

  )+
  facet_wrap(~disasterNumber)

cook_assist |> 
  filter(disasterNumber == 4749 | disasterNumber == 4728 ) |>
  group_by(joinyear, disasterNumber, censusGeoid) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |>
  arrange(desc(claimcount))

cook_assist |> 
  filter((disasterNumber == 4749 | disasterNumber == 4728) & censusGeoid != "NULL" ) |>
  group_by(joinyear, disasterNumber, censusGeoid) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  left_join(blk_grps, by = c( "joinyear" = "year", "censusGeoid" = "bg_id")) %>%    

  ggplot(aes(fill = ihpAmount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "Amount Granted by Census Block Group & Disaster Declaration", caption = element_blank()) +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
   # nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
    labels = scales::comma

  )+
  facet_wrap(~disasterNumber)

```


```{r censustract-shapefiles,  message=FALSE, results='hide'}

tracts2000 <- tracts(state = "17", county = "031", year=2000) %>% mutate(year = 2000)

tracts2010 <- tracts(state = "17", county = "031",year=2010) %>% mutate(year = 2010)

tracts2020 <- tracts(state = "17", county = "031", year=2020) %>% mutate(year = 2020)


tracts2000 <- tracts2000 |> 
  select(
         tract = TRACTCE00,
         year)


tracts2010 <- tracts2010 |> 
  select(
         tract = TRACTCE10,
         year)

tracts2020 <- tracts2020 |> 
  select(
         tract = TRACTCE,
         year)

ce_tracts <- rbind(tracts2000, tracts2010, tracts2020)

```

```{r make-tract-maps-pdfs, eval=FALSE, include=FALSE}
years <- unique(ce_tracts$year)

walk(years, ~ {
  p <- ggplot(filter(ce_tracts, year == .x)) +
    geom_sf(fill = "white", color = "grey20") +
   # geom_sf_text(aes(label = tracts_id), size = 1) +
    coord_sf() +
    theme_void() +
    labs(title = paste("Cook County Census Tracts —", .x))
  
  ggsave(filename = paste0("outputs/maps/cook_censustracts_", .x, ".pdf"),
         plot = p,
         width = 8,
         height = 10)
})
```

```{r ZCTAs, warning = FALSE, message=FALSE, results='hide'}
# ZCTA shapefiles

zipsIL2000 <- zctas(starts_with="60", cb=T, year=2000) %>% mutate(year = 2000)

zipsIL2010 <- zctas(starts_with="60", cb=T, year=2010) %>% mutate(year = 2010)

zipsIL2020 <- zctas(cb=T, starts_with="60", year=2020) %>% mutate(year = 2020)


zipsIL2000 <- zipsIL2000 |> 
  select(ZCTA = ZCTA,
         NAME = NAME,
         year)


zipsIL2010 <- zipsIL2010 |> 
  select(ZCTA = ZCTA5,
         NAME = NAME,
         year)

zipsIL2020 <- zipsIL2020 |> 
  select(ZCTA = ZCTA5CE20,
         NAME = NAME20,
         year)

zips <- rbind(zipsIL2000, zipsIL2010, zipsIL2020)



border <- st_read("inputs/Mapping_FIRMs/Cook_County_Border/Cook_County_Border.shp") |> 
  st_transform("EPSG:6454")

zips <- zips |> 
    st_transform("EPSG:6454") |>

    st_intersection(st_as_sf(border))
  # filter(as.numeric(ZCTA) >=60600 & as.numeric(ZCTA) <= 60900)


# Separate maps (one PDF per year)
years <- unique(zips$year)

walk(years, ~ {
  p <- ggplot(filter(zips, year == .x)) +
    geom_sf(fill = "white", color = "grey20") +
    geom_sf_text(aes(label = ZCTA), size = 2) +
    coord_sf() +
    theme_void() +
    labs(title = paste("Cook County ZCTAs —", .x),
         subtitle = "5-digit ZIP Code Tabulation Areas")
  
  ggsave(filename = paste0("cook_zctas_", .x, ".pdf"),
         plot = p,
         width = 8,
         height = 10)
})
```

# Applicants (Granted and Denied together)


```{r}
#| label: tbl-recentdisasters-bytract
#| tbl-cap: "2023 Disaster Declarations: Claims by Track"

cook_assist |> 
  group_by(year, disasterNumber, tract) %>%
    summarize(claimcount = round(n()),
            granted = sum(ihpAmount > 0),
            denied = sum(ihpAmount < 1),
            ihpAmount = round(sum(ihpAmount, na.rm=TRUE))
  ) |>
  arrange(desc(claimcount))
```

```{r}
#| label: tbl-missing-geoids
#| tbl-cap: "**Applications associated with MISSING censusGeoids.** Applications do have damagedCity and damagedZipCode filled in. Just can't be included with census block group or tract level summaries. For 2023 disasters only."

cook_assist  |> 
  filter(censusGeoid == "NULL") |> 
  group_by(clean_name, damagedZipCode) |> 
  summarize(claimcount = round(n()),
            granted = sum(ihpAmount > 0),
            denied = sum(ihpAmount < 1),
            ihpAmount = round(sum(ihpAmount, na.rm=TRUE))
  )

cook_assist  |> 
  filter(censusGeoid == "NULL") |> 
  group_by(clean_name) |> 
  summarize(claimcount = round(n()),
            granted = sum(ihpAmount > 0),
            denied = sum(ihpAmount < 1),
            ihpAmount = round(sum(ihpAmount, na.rm=TRUE))
  ) |> 
  arrange(desc(claimcount))
```


```{r}
#| label: fig-map-tract-applicants
#| layout-ncol: 2
#| fig-cap: "Geography is Census Tract. Applicants that were missing their `censusGeoid` were excluded from totals."

cook_assist |> 
  filter(censusGeoid != "NULL" ) |>
  group_by(joinyear, disasterNumber, tract) %>%
  filter(!is.na(tract)) |>
  summarize(claimcount = round(n()),
            ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  left_join(ce_tracts, by = c( "joinyear" = "year", "tract" = "tract")) %>%    
  
  ggplot(aes(fill = claimcount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "Applicants by Census Tract & Disaster Declaration", caption = "") +
  theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
    nice.breaks = FALSE,
    na.value = "white",
    show.limits=TRUE,
    name = "Count",
    labels = scales::comma) +
  facet_wrap(~disasterNumber)

cook_assist |> 
  filter(censusGeoid != "NULL" ) |>
  group_by(joinyear, disasterNumber, tract) %>%
  summarize(claimcount = round(n()),
            ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  filter(!is.na(tract)) |>
  
  left_join(ce_tracts, by = c( "joinyear" = "year", "tract" = "tract")) %>%    
  
  ggplot(aes(fill = ihpAmount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "Amount Granted by Census Block Group & Disaster Declaration", caption = element_blank()) +
  theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
    na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
    labels = scales::comma
  )+
  facet_wrap(~disasterNumber)

```





```{r}
#| label: tbl-appllicants-perdisasterdeclaration
#| tbl-cap: "Number of applications for individual assistance received for all declarations in Cook County" 

cook_assist %>% 
  group_by(declarationDate, disasterNumber) %>% 
  summarize(n = n(),
            ihpAmount = sum(ihpAmount),
            haAmount = sum(haAmount))
```

```{r}
#| label: fig-mapzipcodes-applicants
#| fig-cap: "Location of applicants by zipcode and disaster declaration ID"
#| layout-ncol: 2


cook_assist |> 
  group_by(joinyear, disasterNumber, damagedZipCode) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
  full_join(zips, by = c( "joinyear" = "year", "damagedZipCode" = "ZCTA")) %>%    

  ggplot(aes(fill = claimcount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "Applicants by Zip Code & Disaster Declaration", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
    labels = scales::comma

  )+
  facet_wrap(~disasterNumber)

cook_assist |> 
  filter(ihpAmount > 0 & disasterNumber != "NA" & !is.na(disasterNumber) & !is.na(damagedZipCode )) |>
  group_by(joinyear, disasterNumber, damagedZipCode) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
  #full_join(zipcodes, by = c("damagedZipCode" = "ZCTA5CE20")) %>% 
  full_join(zips, by = c("joinyear" = "year", "damagedZipCode" = "ZCTA" )) %>%    

  ggplot(aes(fill = claimcount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "Granted Aid by Zip Code & Disaster Declaration", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
    labels = scales::comma

  )+
  facet_wrap(~disasterNumber)
```


```{r}
#| label: tbl-applicants-for2023disasters
#| tbl-cap: "Number of applications for individual assistance received for the two disaster declarations in Cook County during 2023." 

ind_assist %>% 
    filter(disasterNumber %in% c(4728, 4749) ) |>

  group_by(declarationDate, disasterNumber) %>% 
  summarize(n = n(),
            ihpAmount = sum(ihpAmount),
            haAmount = sum(haAmount))
```


```{r}
#| label: tbl-applicants-withfloodinsurance
#| tbl-cap: "Number of applications for individual assistance received for the two disaster declarations in Cook County during 2023 by if they had flood insurance or not."

ind_assist %>% 
  filter(disasterNumber %in% c(4728, 4749) ) |>
  group_by(clean_name, floodInsurance) %>% 
  summarize(claimcount = n(),
            ihpAmount = round(sum(ihpAmount, na.rm=TRUE)))  %>% 
  arrange(desc(claimcount)) %>%
  pivot_wider(values_from = claimcount, names_from = floodInsurance)
```


```{r}
#| label: tbl-apps-withinsurance-zipcode
#| tbl-cap: "Number of applications per zipcode by if they had flood insurance."


ind_assist %>% 
  group_by(damagedZipCode, floodInsurance) %>% 
  summarize(claimcount = n()) %>% 
  arrange(desc(claimcount)) %>%
 pivot_wider(values_from = claimcount, names_from = floodInsurance)

```


```{r}
#| label: fig-mapzipcodes-applicants-2023
#| fig-cap: "Location of applicants - ZCTAs. NOTE: mapped with ZCTAs but Zip Codes were the variable reported in FEMA's dataset. 2023 disasters only."


ind_assist |> 
  filter(disasterNumber == 4749 | disasterNumber == 4728) |>
  group_by(joinyear, damagedZipCode) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
 # full_join(zipcodes, by = c("damagedZipCode" = "ZCTA5CE20")) %>%  
    left_join(zips, by = c("joinyear" = "year", "damagedZipCode" = "ZCTA" )) %>%    

  ggplot(aes(fill = claimcount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "Applicants by Zip Code", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
      labels = scales::comma

  )
```

```{r}
#| label: fig-mapzipcodes-applicants-wFloodInsurance
#| fig-cap: "Location of applicants with Flood Insurance. 2023 disasters only."

ind_assist |> 
  filter(disasterNumber == 4749 | disasterNumber == 4728 & floodInsurance == TRUE) |>
  group_by(joinyear, damagedZipCode) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
 # full_join(zipcodes, by = c("damagedZipCode" = "ZCTA5CE20")) %>%  
    left_join(zips, by = c( "joinyear" = "year", "damagedZipCode" = "ZCTA")) %>%    

  ggplot(aes(fill = claimcount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "Applicants with Flood Insurance by Zip Code", 
       caption = "Disaster Declarations 4729 and 4728 only") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "blue", low = "black",
  na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
  labels = scales::comma
  )
```


# Applications with Grants Awarded


```{r}
table(ind_assist$disasterNumber, ind_assist$ownRent)

# 	Damaged Dwelling Residence Type (e.g., single-family home, apartment). A - Apartment; B - Boat; C - Condo; H - House/Duplex; M - Mobile Home; N - Non-Traditional; O - Other; TH - Townhouse; T - Travel Trailer; ALF - Assisted Living Facility; MIL - Military Housing; CD - College Dorm; CF - Correctional Facility
table(ind_assist$residenceType, ind_assist$disasterNumber)

table(ind_assist$ownRent, ind_assist$disasterNumber)

```


```{r}
#| label: fig-mapzipcodes-applicants-alldisasters
#| fig-cap: "All disaster declarations since 2010. Aggregated to zip code. Only includes those that received IHP funds."
#| layout-ncol: 2


cook_assist |> 
  filter(disasterNumber %in% c(1935, 4116, 4728, 4749) ) |>
    filter(ihpAmount > 0 &
           # disasterNumber != "NA" & !is.na(disasterNumber) & 
             !is.na(damagedZipCode )) |>

  group_by(joinyear, damagedZipCode, disasterNumber) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
  #left_join(zipcodes, by = c("damagedZipCode" = "ZCTA5CE20")) %>%   
    left_join(zips, by = c( "joinyear" = "year", "damagedZipCode" = "ZCTA")) %>%    

  ggplot(aes(fill = ihpAmount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "Granted Aid by Zip Code & Disaster Declaration", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  #na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Dollars",
    labels = scales::dollar

  )+
  facet_wrap(~disasterNumber)

cook_assist |> 
  filter(disasterNumber %in% c(1935,4116, 4728, 4749) ) |>
  filter(ihpAmount > 0 & 
          # disasterNumber != "NA" & !is.na(disasterNumber)  & 
           !is.na(damagedZipCode )
         ) |>
  group_by(joinyear, disasterNumber, damagedZipCode) %>%
    summarize(claimcount = round(n()),
              
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
  left_join(zips, by = c( "joinyear" = "year", "damagedZipCode" = "ZCTA")) %>%    

  ggplot(aes(fill = claimcount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "Granted Aid by Zip Code & Disaster Declaration", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
 # na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
    labels = scales::comma

  )+
  facet_wrap(~disasterNumber)
```


```{r}
#| label: tbl-ihpamounts
#| tbl-cap: "`ihpAmount` includes amount awarded for Housing Assistance (HA) and Other Needs Assistance (ONA). NOTE: ONA values are already included in IHP values."

ind_assist %>% 
  filter(ihpAmount > 0) |> 
  group_by(declarationDate, disasterNumber) %>% 
  summarize(n = n(),
            ihpAmount = sum(ihpAmount),
            haAmount = sum(haAmount))
```


```{r}
#| label: tbl-apps-withinsurance
#| tbl-cap: "Applications with flood premiums paid from the two disaster declarations (`fipAmount > 0)`. 160 applications did not have flood insurance and had a flood insurance premium greater than $0. (which doesn't make sense?)."


ind_assist %>% 
  filter(fipAmount > 0) |> 
  group_by(declarationDate, disasterNumber, floodInsurance) %>% 
  summarize(n = n())
```


```{r}
#| label: tbl-2023applicantswithinsurance
#| tbl-cap: "Applications awarded funds by Municipality and flood insurance. Both Flood Events in 2023"


ind_assist %>% 
  filter(disasterNumber %in% c(4728, 4749) ) |>

  filter(ihpAmount > 0) |>
  group_by(clean_name, floodInsurance) %>% 
  summarize(claimcount = n(),
                #ihpAmount = round(sum(ihpAmount, na.rm=TRUE)),
           )  %>% 
  arrange(desc(claimcount)) %>%
  pivot_wider(values_from = claimcount, names_from = floodInsurance) %>% 
  arrange(desc(`TRUE`)) |> 
  DT::datatable(rownames = FALSE)
```



```{r}
#| label: tbl-treated-zipcodes
#| tbl-cap: "Zip Codes that would be considered 'Treated' due to experiencing a flood event. Maybe need to create some kind of threshold for treatment intensity?"

ind_assist |> 
  filter(ihpAmount > 0) |>
  group_by(year, disasterNumber, damagedZipCode) |>
  summarize(claimcount = n(),
           ) |> 
  write_csv("./data/processed/treated_zipcodes.csv")

ind_assist |> 
  filter(ihpAmount > 0) |>
  group_by(year, disasterNumber, censusGeoid) |>
  summarize(claimcount = n(),
            granted = sum(ihpAmount > 0, na.rm=TRUE),
            denied = sum(ihpAmount > 0, na.rm=TRUE),
            ihpAmount = sum(ihpAmount, na.rm=TRUE),
            flood_damage = sum(floodDamageAmount, na.rm=TRUE),
            renters = sum(ownRent == "R", na.rm = TRUE),
            owners = sum(ownRent == "O", na.rm = TRUE),
            home_damage_amount = sum(homeDamage == TRUE, na.rm=TRUE)
           ) |> write_csv("./data/processed/treated_census_blocks.csv")

ind_assist %>% 
  filter(ihpAmount > 0) |>
  mutate(DisasterYear = paste(year, " - ", disasterNumber)) |>
  group_by(DisasterYear, damagedZipCode) %>% 
  summarize(claimcount = n(),
           )  %>% 
  pivot_wider(values_from = claimcount, names_from = DisasterYear) %>% 
  DT::datatable(rownames = FALSE)
```



## July Storm

```{r}
#| label: tbl-julydisaster
#| tbl-cap: "July Disaster Declaration. Number of applicants who were awarded funds and had flood damage."

ind_assist %>% 
    filter(disasterNumber == 4728 & ihpAmount > 0 & floodDamage == TRUE) |>
  group_by(clean_name, residenceType
           ) %>% 
  summarize(claimcount = n(),
            flooded = sum(floodDamage == TRUE, na.rm=TRUE),
            awardedfunds = round(sum(ihpAmount, na.rm=TRUE))) %>% 
  arrange(desc(claimcount)) |> 
  DT::datatable(rownames = FALSE)
```

```{r}
#| label: fig-julydisaster
#| fig-cap: "July Disaster Declaration. Number of applicants who were awarded funds and had flood damage."
#| layout-ncol: 2


ind_assist |> 
  filter(disasterNumber == 4728 & ihpAmount > 0 & floodDamage==TRUE) |>
  group_by(damagedZipCode) %>%
    summarize(claimcount = n(),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode),
         claimcount = round(claimcount))|>
 # full_join(zipcodes, by = c("damagedZipCode" = "ZCTA5CE20")) %>% 
     full_join(zips[zips$year==2020, ], by = c("damagedZipCode" = "ZCTA")) %>%    
  ggplot(aes(fill = claimcount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "July Storm - Claims by Zip Codes for Flood Damage", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank()) +
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
   # nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
  )


ind_assist |> 
  filter(disasterNumber == 4728 & ihpAmount > 0
         & floodDamage==TRUE) |>
  group_by(joinyear, damagedZipCode) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
  # full_join(zips, by = c("joinyear" = "year", "damagedZipCode" = "ZCTA")) %>%    
     full_join(zips[zips$year==2020, ], by = c("damagedZipCode" = "ZCTA", "joinyear" = "year")) %>%    


  ggplot(aes(fill = ihpAmount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "July Storm - IHP Grants by Zip Codes for Flood Damage", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Dollars",
  labels = scales::dollar
  )
```

## September Storm


```{r}
#| label: fig-2010storm
#| fig-cap: "2010 Disaster Declaration. Number of applicants who were awarded funds and had flood damage."
#| layout-ncol: 2


ind_assist |> 
  filter(disasterNumber == 1935 & ihpAmount > 0) |>
  group_by(joinyear, damagedZipCode) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
full_join(zips[zips$year==2010, ], by = c("damagedZipCode" = "ZCTA", "joinyear" = "year")) %>%    
  ggplot(aes(fill = claimcount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "September Storm - Claims by Zip Codes", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
    labels = scales::comma
  )

ind_assist |> 
  filter(disasterNumber == 1935 & ihpAmount > 0) |>
  group_by(joinyear, damagedZipCode) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
full_join(zips[zips$year==2010, ], by = c("damagedZipCode" = "ZCTA", "joinyear" = "year")) %>%    

  ggplot(aes(fill = ihpAmount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "September Storm - IHP Grants by Zip Codes", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Dollars",
  labels = scales::dollar
  )
```





```{r}
#| label: tbl-2010storm
#| tbl-cap: "September Disaster Declaration. Number of applicants who received funds."


ind_assist %>% 
  filter(disasterNumber == 1935 & ihpAmount > 0) |>
  group_by(clean_name, residenceType#, floodInsurance
           ) %>% 
  summarize(claimcount = n(),
            awardedfunds = round(sum(ihpAmount, na.rm=TRUE))) %>% 
  arrange(desc(claimcount)) |> 
  DT::datatable(rownames = FALSE)
```


## 2010 Storm


## 2013 Storm


```{r}
#| label: fig-2013storm
#| fig-cap: "September Disaster Declaration. Number of applicants who were awarded funds and had flood damage."
#| layout-ncol: 2

ind_assist |> 
  filter(disasterNumber == 4116 & ihpAmount > 0) |>
  group_by(joinyear, damagedZipCode) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
full_join(zips[zips$year==2010, ], by = c("damagedZipCode" = "ZCTA", "joinyear" = "year")) %>%    
  ggplot(aes(fill = claimcount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "September Storm - Claims by Zip Codes", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Count",
    labels = scales::comma

  )

ind_assist |> 
  filter(disasterNumber == 4116 & ihpAmount > 0) |>
  group_by(joinyear, damagedZipCode) %>%
    summarize(claimcount = round(n()),
                ihpAmount = round(sum(ihpAmount, na.rm=TRUE))) |> 
  mutate(damagedZipCode = as.character(damagedZipCode))|>
full_join(zips[zips$year==2010, ], by = c("damagedZipCode" = "ZCTA", "joinyear" = "year")) %>%    

  ggplot(aes(fill = ihpAmount)) +
  geom_sf(aes(geometry = geometry), color = "black") +
  labs(title = "September Storm - IHP Grants by Zip Codes", caption = "") +
    theme_void() +
  theme(axis.ticks = element_blank(), axis.text = element_blank())+# +#+
  scale_fill_steps2(
    high = "darkblue", low = "black",
  na.value = "white",
    nice.breaks = FALSE,
    show.limits=TRUE,
    name = "Dollars",
  labels = scales::dollar
  )
```



```{r}
#| label: tbl-2013storm
#| tbl-cap: "September Disaster Declaration. Number of applicants who received funds."


ind_assist %>% 
  filter(disasterNumber == 4116 & ihpAmount > 0) |>
  group_by(clean_name, residenceType#, floodInsurance
           ) %>% 
  summarize(claimcount = n(),
            awardedfunds = round(sum(ihpAmount, na.rm=TRUE))) %>% 
  arrange(desc(claimcount)) |> 
  DT::datatable(rownames = FALSE)
```


# Descriptive Stats

```{r eval=FALSE}
table(ind_assist$residenceType, ind_assist$disasterNumber)

table(ind_assist$grossIncome, ind_assist$disasterNumber)

ind_assist <- ind_assist |> mutate(across(c(disasterNumber, damagedZipCode), as.factor))

# datasummary_skim(ind_assist, type = "dataset")
# datasummary_skim(ind_assist, type = "numeric")
# datasummary_skim(ind_assist, type = "categorical")

datasummary_balance(~disasterNumber, data = ind_assist %>% 
                      filter(ihpAmount > 0 & floodDamage == TRUE))

```
