---
title: "Q2 Marginal Effects"
format: html
---

# Question 2

## Table 15: Question 2 Main Model

```{r}
library(marginaleffects)

bldg_sfha <- bldg_sfha |> mutate(event = sale_date> new_info_released)

bldg_sfha <- bldg_sfha |> mutate(highff_post = high_ff_score == TRUE &  sale_date > new_info_released )


## change type is for effective maps
triad_mod = feols(log(sale_price) ~ change_type * high_ff_score * event * Triad | pin + sale_year, vcov = ~pin10, data= bldg_sfha)

etable(triad_mod)


# a specific scenario I'm curious about
example_grid = data.frame(event = TRUE, change_type = "Never SFHA", high_ff_score = TRUE, Triad = "City")

grid_preds <- avg_comparisons(
  triad_mod,
  variables = c("event", "high_ff_score"),
  cross = TRUE
)

grid_preds

```


```{r}
avg_results <- avg_comparisons(
  triad_mod,
  variables = list(change_type ="sequential")
  )
avg_results
```


```{r}
avg_results <- avg_comparisons(
  triad_mod,
  variables = list("event" = c(FALSE, TRUE)),
  by = "change_type")
avg_results
```


```{r}
bldg_sfha <- bldg_sfha |> 
  group_by(pin) |>
  mutate(pin_num = as.numeric(pin),
    # ff_group = ifelse(high_ff_score==TRUE & sale_date > new_info_released, as.character(min(sale_year[sale_date > new_info_released])), "0")) |>
      ff_group = ifelse(high_ff_score==TRUE & sale_date > new_info_released, "2020", "0")) |>

  ungroup()

library(etwfe)
mod_etwfe <- etwfe(
  fml  = log(sale_price) ~ 1, 
  data = bldg_sfha, 
  ivar   = pin_num, 
  tvar = sale_year,
  tref = "2019",
  gref = "0",
  gvar = ff_group, 
  vcov = ~pin10
)

emfx(mod_etwfe)

```

```{r}
mod_etwfe2 <- etwfe(
  fml  = log(sale_price) ~ 1, 
  data = bldg_sfha, 
  ivar = pin, 
  tvar = sale_year,
  tref = "2019",
  gref = "0",
  gvar = ff_group, 
  vcov = ~pin10,
  xvar = Triad)

emfx(mod_etwfe2)
emfx(mod_etwfe2, type = "group")


```


```{r}
models <- list(
  "County" = feols(log_price ~ prelim_sfha_category * high_ff_score * event | pin + sale_year, data= bldg_sfha, cluster = ~ pin10),
  
  "Triad Interactions" = feols(log_price ~ prelim_sfha_category * high_ff_score * event + Triad | pin + sale_year, data= bldg_sfha, cluster = ~ pin10)

)
```


```{r}
### this one works great!
never_sfha_effect <- avg_comparisons(
  triad_mod,
  variables = "event",
  newdata = datagrid(
    change_type = "Never SFHA",
    "high_ff_score"   = c(TRUE,FALSE)
  ),
   by = NULL)

never_sfha_effect
```


```{r}
triad_mod_pre <- feols(log_price ~ prelim_sfha_category * high_ff_score * event * Triad | pin + sale_year, data = bldg_sfha, cluster = ~ pin10)

## only shoes coefficient for City
never_sfha_effect_byTriad <- avg_comparisons(
  triad_mod_pre,
  variables = "event",
  newdata = datagrid(
    prelim_sfha_category = "Never SFHA",
    high_ff_score   = c(TRUE,FALSE)
  ),
  by = "Triad")

never_sfha_effect_byTriad
```
```{r}
always_sfha_effect <- avg_comparisons(
  triad_mod_pre,
  variables = "event",
  newdata = datagrid(
    prelim_sfha_category = "Always SFHA",
        high_ff_score   = c(FALSE,TRUE)
),
   by = NULL
)

always_sfha_effect
```

```{r}
always_sfha_effect_byTriad <- avg_comparisons(
  triad_mod_pre,
  variables = "event",
  newdata = datagrid(
    prelim_sfha_category = "Always SFHA",
        "high_ff_score"   = c(TRUE,FALSE)
),
   by = "Triad"
)

always_sfha_effect_byTriad
```

## Q2 Robustness Checks

```{r}
models <- list(
  "South" = feols(log_price ~ prelim_sfha_category * high_ff_score * event | pin + sale_year, data = bldg_sfha |> filter(Triad == "South"), cluster = ~pin10),
  "North" = feols(log_price ~ prelim_sfha_category * high_ff_score* event | pin + sale_year, data = bldg_sfha |> filter(Triad == "North"), cluster = ~pin10),
    "City" = feols(log_price ~ prelim_sfha_category * high_ff_score * event | pin + sale_year, data = bldg_sfha |> filter(Triad == "City"), cluster = ~pin10)
)

modelsummary(
  models,
  output     = "gt",
  stars      = TRUE,
  estimate   = "{estimate}{stars}",
  statistic  = "({std.error})",
  gof_omit   = "IC|Log|Adj|AIC|BIC",
#  add_rows   = data.frame(Term = "SE clustered", Value = "pin"),
  title      = "Pre-event slope tests by Triad"
)
```


```{r}
models <- list(
  "South" = feols(log_price ~ prelim_sfha_category * highff_post | pin + sale_year, data = bldg_sfha |> filter(Triad == "South"), cluster = ~pin10),
  "North" = feols(log_price ~ prelim_sfha_category * highff_post | pin + sale_year, data = bldg_sfha |> filter(Triad == "North"), cluster = ~pin10),
    "City" = feols(log_price ~ prelim_sfha_category * highff_post | pin + sale_year, data = bldg_sfha |> filter(Triad == "City"), cluster = ~pin10)
)

modelsummary(
  models,
  output     = "gt",
  stars      = TRUE,
  estimate   = "{estimate}{stars}",
  statistic  = "({std.error})",
  gof_omit   = "IC|Log|Adj|AIC|BIC",
#  add_rows   = data.frame(Term = "SE clustered", Value = "pin"),
  title      = "Pre-event slope tests by Triad"
)
```


## Ordinal Risk Variable

